import type { Metadata } from "next";
import "../styles/globals.css";
import {} from "@/components/SidebarCart";
import { SidebarCartWrapper } from "@/components/SidebarCartWrapper";
import { CartProvider } from "@/context/CartContext";
import { UserProvider } from "@/context/UserContext";
import { CheckoutProvider } from "@/context/CheckoutContext";
import { PaymentProvider } from "@/context/PaymentContext";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <CartProvider>
            <CheckoutProvider>
              <PaymentProvider>
                <SidebarCartWrapper>
                  {children}
                  <Footer />
                </SidebarCartWrapper>
              </PaymentProvider>
            </CheckoutProvider>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
